groups:
  - id: service
    prefix: service
    type: resource
    brief: >
      A service instance.
    attributes:
      - id: name
        type: string
        requirement_level: required
        brief: >
          Logical name of the service.
        note: >
          MUST be the same for all instances of horizontally scaled services.
          If the value was not specified, SDKs MUST fallback to `unknown_service:` concatenated
          with [`process.executable.name`](process.md#process), e.g. `unknown_service:bash`.
          If `process.executable.name` is not available, the value MUST be set to `unknown_service`.
        examples: ["shoppingcart"]
      - id: version
        type: string
        brief: >
          The version string of the service API or implementation. The format is not defined by these conventions.
        examples: ["2.0.0", "a01dbef8a"]
