include_fragments = true

accept = ["200..=299", "403"]

remap = [
  # workaround for https://github.com/lycheeverse/lychee/issues/1729
  "https://github.com/(.*?)/(.*?)/blob/(.*?)/(.*#.*)$ https://raw.githubusercontent.com/$1/$2/$3/$4",
  "https://docs.oracle.com/(.*)#.*$ https://docs.oracle.com/$1",
  "https://www.ibm.com/docs/api/v1/content/SSYKE2_8.0.0/openj9/(.*)#.*$ https://www.ibm.com/docs/api/v1/content/SSYKE2_8.0.0/openj9/$1",
  "https://docs.docker.com/reference/(.*)#.*$ https://docs.docker.com/reference/$1",
  "https://javadoc.io/(.*)#.*$ https://javadoc.io/$1",
  "https://github.com/(.*)#issuecomment-.*$ https://github.com/$1",
  "https://github.com/(.*)#discussion_r.*$ https://github.com/$1",
]

exclude = [
  "^https://www.foo.bar",
  # excluding links to pull requests and issues is done for performance
  "^https://github.com/open-telemetry/semantic-conventions/(pull|issues)/\\d+$",
  "^https://github.com/open-telemetry/opentelemetry-specification/(pull|issues)/\\d+$",
  # TODO (lmolkova) treat timeout as not a failure?
  "^https://www.intersystems.com",
  "^https://gcc.gnu.org",
]

# better to be safe and avoid failures
max_retries = 6

# better to be safe and avoid failures
timeout = 60

# insecure is currently needed for https://osi-model.com
insecure = true

# this helps slow down the rate of requests to avoid rate limiting
max_concurrency = 4
