include_fragments = true

accept = ["200..=299", "403"]

exclude = [
    "^https://www.foo.bar",
    # excluding links to pull requests and issues is done for performance
    "^https://github.com/open-telemetry/semantic-conventions/(pull|issues)/\\d+$",
    "^https://github.com/open-telemetry/opentelemetry-specification/(pull|issues)/\\d+$"
]

# better to be safe and avoid failures
max_retries = 6

# insecure is currently needed for https://osi-model.com
insecure = true
