# cspell:ignore ebpf matic postgres protable
plugins:
  "@textlint/textlint-plugin-text":
    extensions:
      - ".yaml"
      - ".yml"

filters:
  allowlist:
    allow:
      # Don't check registry .yml file fields for language, repo,URL and tags:
      - '/^\s*(?:language|repo|name|docs|url|website): .*$/m'
      - /^(?:tags):(\s*-.+$)*/m
      # Hugo template syntax:
      - /{{.*?}}/
      - /{{%.*?%}}/
      # Custom header anchors in markdown headings:
      - /{#.*?}/
      # src attribute in figure Hugo template:
      - /src=".*?"/
      # Other:
      - /(<|\()https?:\/\/.*?(>|\))/ # Raw URLs
      - /`.*`/ # Raw code in backticks
      - /attributes-registry, \(e.g. http, cloud, db\)/ # Example of Component names in changelog files
      - /\(e.g., http, databases/ # Example of domains names in migration notes
      - /\"id\":/ # IDs in JSON files
      - /\n\s*(-\s)?(\S+):/ # YAML keys, with optional list marker
      - /\n\s*(-\s)?(id|value|examples|metric_name|ref|component):\s(\[.+\]|.+)/ # Values for YAML keys in allowed list are not checked
      - /examples:\n?.+\[(.|\n)([^\]])*]/ # Examples YAML key with list of values, allowing for multi-line lists
  comments: true
rules:
  common-misspellings:
    # Misspellings to be ignored (case-insensitive)
    ignore: [
      GAE
    ]
  period-in-header: true
  terminology:
    defaultTerms: false
    skip: []
    exclude:
      - 'bug[- ]fix(es)?'
      - 'readme(s)?'
      - 'to-?do(s)?(?=[ ,.])'
      - "indexes\\b"
      - 'web[- ]?site(s)?'
