name: Propose new semantic conventions
description: Propose new conventions you'd like to see in the OpenTelemetry project
labels: ["enhancement", "experts needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in contributing to the OpenTelemetry Semantic Conventions!

        Substantial changes to the conventions follow [OTel project management]
        (https://github.com/open-telemetry/community/blob/main/project-management.md) process
        and usually require a group of people who are familiar with the domain,
        are involved with instrumentation efforts, and are committed to be the point of contact for
        pull requests, issues, and questions in this area.

        Creating a new issue here is a great first step to find others interested in collaborating.
  - type: textarea
    attributes:
      label: Propose new conventions
      description: |
        Please provide a brief description of the conventions, including
        telemetry signals you'd like to define.

        Consider specifying which instrumentations or systems would implement these
        conventions and the benefits they would bring to the ecosystem.
    validations:
      required: true
