name: Propose new semantic conventions
description: Propose new conventions you'd like to be part of the OpenTelemetry project
labels: ["enhancement", "triage:needs-triage", "experts needed"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to fill out the entire form below, providing as much context as you can in order to help us triage the proposal as quickly as possible.

        Before filing the proposal, please be sure you have searched through [existing issues](https://github.com/open-telemetry/semantic-conventions/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aenhancement+label%3Aarea:new) to see if an existing issue covers your proposal.

        Additionally, make sure to read and follow the guidelines on [Project Proposal](https://github.com/open-telemetry/community/blob/main/project-management.md#project-management), in case the proposal is for a new set of conventions/working group.
  - type: dropdown
    id: area
    attributes:
      label: Area(s)
      description: Which area(s) does your new conventions concern? If none fits, please select `area:new`
      multiple: true
      options:
      - area:new
      # NOTE: The list below is autogenerated using `make generate-gh-issue-templates`
      # DO NOT manually edit it.
      # Start semconv area list
      - area:browser
      - area:client
      - area:cloud
      - area:code
      - area:container
      - area:db
      - area:destination
      - area:device
      - area:disk
      - area:error
      - area:exception
      - area:host
      - area:http
      - area:k8s
      - area:messaging
      - area:network
      - area:oci
      - area:os
      - area:process
      - area:rpc
      - area:server
      - area:source
      - area:thread
      - area:tls
      - area:url
      - area:user-agent
      # End semconv area list
  - type: textarea
    attributes:
      label: Is your change request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
