groups:
  - id: registry.build
    prefix: build
    type: attribute_group
    brief: >
     This group describes attributes specific to builds (ci).
    attributes:
      - id: artifact.name
        type: string
        stability: experimental
        brief: >
          The human readable file name of the build artifact, often generated
          by release utilities to include the package name and version.
        examples: ['golang-binary-amd64-v0.1.0', 'docker-image-amd64-v0.1.0', 'release-1.tar.gz', 'file-name-package.tar.gz']
      - id: artifact.version
        type: string
        stability: experimental
        brief: >
          The version of the build artifact.
        examples: ['v0.1.0', '1.2.1', '122691-build']
      - id: artifact.purl
        type: string
        stability: experimental
        brief: >
          The [Package URL](https://github.com/package-url/purl-spec) of the
          build artifact, providing a standard way to identify and locate the
          artifact.
        examples: ['pkg:github/package-url/purl-spec@1209109710924', 'pkg:npm/foo@12.12.3']
      - id: artifact.hash
        type: string
        stability: experimental
        brief: >
          The [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf),
          often found in checksum.txt on a release of the build artifact and
          used to verify pakage integrity.
        examples: ['9ff4c52759e2c4ac70b7d517bc7fcdc1cda631ca0045271ddd1b192544f8a3e9']
      - id: attestation.id
        type: string
        stability: experimental
        brief: >
          The id of the build [software attestation](https://slsa.dev/attestation-model).
        examples: ['123']
      - id: attestation.hash
        type: string
        stability: experimental
        brief: >
          The [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf),
          of the built attestation. Some envelopes in the software attestation
          space also refer to this as the [digest](https://github.com/in-toto/attestation/blob/main/spec/README.md#in-toto-attestation-framework-spec).
        examples: ['1b31dfcd5b7f9267bf2ff47651df1cfb9147b9e4df1f335accf65b4cda498408']
