groups:
  - id: registry.build
    prefix: build
    type: attribute_group
    brief: >
     This group describes attributes specific to builds (ci).
    attributes:
      - id: artifact.name
        type: string
        stability: experimental
        brief: >
          The name of the build artifact.
        examples: ['golang-binary-amd64-v0.1.0', 'docker-image-amd64-v0.1.0']
      - id: artifact.id
        type: string
        stability: experimental
        brief: >
          The id of the build artifact.
        examples: ['120912']
      - id: artifact.version
        type: string
        stability: experimental
        brief: >
          The version of the build artifact.
        examples: ['v0.1.0', '1.2.1', '122691-build']
      - id: artifact.sha
        type: string
        stability: experimental
        brief: >
          The sha (checksum) of the build artifact.
        examples: ['9ff4c52759e2c4ac70b7d517bc7fcdc1cda631ca0045271ddd1b192544f8a3e9']
      - id: attestation.id
        type: string
        stability: experimental
        brief: >
          The id of the build attestation.
        examples: ['123']
      - id: attestation.sha
        type: string
        stability: experimental
        brief: >
          The sha (checksum) of the build attestation.
        examples: ['1b31dfcd5b7f9267bf2ff47651df1cfb9147b9e4df1f335accf65b4cda498408']

