groups:
  - id: registry.build
    prefix: build
    type: attribute_group
    brief: >
     This group describes attributes specific to builds (ci).
    attributes:
      - id: attestation.id
        type: string
        stability: experimental
        brief: >
          The id of the build [software attestation](https://slsa.dev/attestation-model).
        examples: ['123']
      - id: attestation.hash
        type: string
        stability: experimental
        brief: >
          The full [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf),
          of the built attestation. Some envelopes in the software attestation
          space also refer to this as the [digest](https://github.com/in-toto/attestation/blob/main/spec/README.md#in-toto-attestation-framework-spec).
        examples: ['1b31dfcd5b7f9267bf2ff47651df1cfb9147b9e4df1f335accf65b4cda498408']
