groups:
  - id: registry.pipeline
    prefix: pipeline
    type: attribute_group
    brief: >
     This group describes attributes specific to pipelines.
    attributes:
      - id: name
        type: string
        stability: experimental
        brief: >
          The name of the pipeline.
        examples: ['build_go_project', 'deploy_to_k8s', 'data pipeline', 'spark pipeline']
      - id: id
        type: string
        stability: experimental
        brief: >
          The id of the pipeline.
        examples: ['120912']
      - id: step.name
        type: string
        stability: experimental
        brief: >
          The name of the step within a pipeline.
        examples: ['golang lint', 'go build', 'go test', 'transform data']
      - id: step.id
        type: string
        stability: experimental
        brief: >
          The id of the step within a pipeline.
        examples: ['12097']
      - id: step.type
        type: string
        stability: experimental
        brief: >
          The type of the step within a pipeline.
        examples: ['build', 'test', 'deploy']
      - id: step.runner.name
        type: string
        stability: experimental
        brief: >
          The name of the runner executing the step within a pipeline.
        examples: ['ubuntu-runner-latest']
      - id: step.runner.id
        type: string
        stability: experimental
        brief: >
          The id of the runner executing the step within a pipeline.
        examples: ['1289']
      - id: step.runner.system
        type: string
        stability: experimental
        brief: >
          OS system attributes of the runner acorrding to the [OS system attributes](./os.md).
        examples: ['system.os.name']
