groups:
  - id: service
    prefix: service
    type: resource
    brief: >
      A telemetry source. OpenTelemetry has adopted a broad interpretation such that every
      telemetry source is a service. Examples include, but are not limited to: web services,
      hosts, mobile applications, browser application, edge computing devices, functions as
      a service, databases, message brokers, etc. Specific types of telemetry sources may have
      additional conventions defining domain specific information, but the `service`
      conventions are applicable to all telemetry sources.
    attributes:
      - id: name
        type: string
        stability: stable
        requirement_level: required
        brief: >
          Logical name of the service.
        note: >
          MUST be the same for all instances of horizontally scaled services.
          If the value was not specified, SDKs MUST fallback to `unknown_service:` concatenated
          with [`process.executable.name`](process.md#process), e.g. `unknown_service:bash`.
          If `process.executable.name` is not available, the value MUST be set to `unknown_service`.
        examples: ["shoppingcart"]
      - id: version
        type: string
        stability: stable
        brief: >
          The version string of the service API or implementation. The format is not defined by these conventions.
        examples: ["2.0.0", "a01dbef8a"]
