groups:
  - id: service
    type: resource
    brief: >
      A service instance.
    stability: stable
    attributes:
      - ref: service.name
        requirement_level: required
      - ref: service.version
