name: 'Prepare new issue'
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  prepare-new-issue:
    permissions:
      issues: write # required for labeling issues
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'open-telemetry' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run prepare-new-issue.sh
        run: ./.github/scripts/prepare-new-issue.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: ${{ github.event.issue.body }}
          OPENER: ${{ github.event.issue.user.login }}
